remote_theme: daviddarnes/garth
title: "Mikhail Ilin web log"
url: "https://ilin.pt"

email: mikhail@ilin.pt
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
twitter_username: pstrnc
github_username:  sbrin

# Build settings
# theme: minima
plugins:
  - jekyll-feed

# Pagination
paginate: 5
paginate_path: blog/page:num

collections:
  # posts:
  #   title: Blog # Needed for Siteleaf
  #   output: true
  #   description: "This is merely a demo, find out more [about Garth](about)" # The post list page content
  # stuff:
  #   title: Stuff
  #   output: true
  #   description: "Some stuff I made"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
