remote_theme: daviddarnes/garth
title: "Mikhail Ilin web log"
url: "https://ilin.pt"

email: mikhail@ilin.pt
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
twitter_username: pstrnc
github_username:  sbrin

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-feed

# Pagination
paginate: 10
paginate_path: blog/page:num

collections:
  posts:
    output: true
    description: "My name is Mikhail Ilin and I identify myself as a random stuff engineer. Most of the things I like are related to web technologies, music or design. [My GitHub](https://github.com/sbrin), [Twitter](https://twitter.com/ilin_pt) and [LinkedIn](https://www.linkedin.com/in/mihaililin/)"
  stuff:
    title: Stuff
    output: true
    description: "Some stuff I made"

# defaults:
#   -
#     scope:
#       path: ""
#       type: pages
#     values:
#       layout: page # Default layout
#   -
#     scope:
#       path: ""
#       type: posts
#     values:
#       layout: post # Default layout
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

webrick:
  headers:
    Content-Security-Policy: "default-src * 'unsafe-inline' 'unsafe-eval'; script-src * 'unsafe-inline' 'unsafe-eval'; connect-src * 'unsafe-inline'; img-src * data: blob: 'unsafe-inline'; frame-src *; style-src * 'unsafe-inline';"

favicon: "data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>💭</text></svg>"