remote_theme: daviddarnes/garth
title: "Mikhail Ilin web log"
url: "https://ilin.pt"

email: mikhail@ilin.pt
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
twitter_username: pstrnc
github_username:  sbrin

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

# Pagination
paginate: 10
paginate_path: blog/page:num

collections:
  posts:
    title: 🏡 # Needed for Siteleaf
    output: true
    description: "This is merely a demo, find out more [about Garth](about)" # The post list page content
  stuff:
    title: Stuff
    output: true
    description: "Some stuff I made"

# defaults:
#   -
#     scope:
#       path: ""
#       type: pages
#     values:
#       layout: page # Default layout
#   -
#     scope:
#       path: ""
#       type: posts
#     values:
#       layout: post # Default layout
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

webrick:
  headers:
    Content-Security-Policy: "default-src * 'unsafe-inline' 'unsafe-eval'; script-src * 'unsafe-inline' 'unsafe-eval'; connect-src * 'unsafe-inline'; img-src * data: blob: 'unsafe-inline'; frame-src *; style-src * 'unsafe-inline';"